### PR TITLE
Improved Code Quality

### PR DESCRIPTION
**Pull request by FalconHeart**
**What PR Does**
Improved Code Quality

### CODE REVIEW

**Comment by FalconHeart** [comment]
Hello Sir.
I have done what you suggested and fixed multiple style/quality issues with the code. 
Is the review any better now?

**Comment by FalconHeart** [comment]
Hello Sir,
I'm just checking whether anything changed.

**Review by BryanAim — COMMENTED** [review]
How's it going so far?

**Review by BryanAim — COMMENTED** [review]
I see that some checks are failing, I'll review them first before merging

**Comment by FalconHeart** [comment]
> How's it going so far?

I added the ESLint configurations, yet I am not skilled enough to know how to fix most of the quality errors.

**Comment by FalconHeart** [comment]
Just a quick question sir,
does the codacy review start up automatically or do you have to start it manually?

**Review by BryanAim — APPROVED** [review]
All checks passing now, nice work!

**Pull request merged**
